### PR TITLE
Remove usage of get-it dependency.

### PR DESCRIPTION
**Pull request by justkawal**
- Removes usage of get-it
- Converts following classes to custom Singleton Class.
    - StoreService
    - DaemonService

```dart
class SingletonClass {
  // Variable to hold the static non-changing reference to a class object on a run.
  static final SingletonClass _singleton = SingletonClass._();
  
  // Private Constructor
  SingletonClass._();

  // get the same instance again and again.
  static SingletonClass get instance => _singleton;
  
  //  [ optional ]  method if want to initialize the objects
  void reInitialize() { ..... }
}
```

### CODE REVIEW

**Comment by leonardocustodio** [comment]
Awesome job, I will test in a few minutes

**Review by leonardocustodio — APPROVED** [review]
lgtm, thank you for your contribution

**Comment by leonardocustodio** [comment]
I can't merge though if you don't sign the commits: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by justkawal** [comment]
Sorry about that, Will do it by eod….

**Comment by justkawal** [comment]
Done

**Comment by leonardocustodio** [comment]
Doesn't seem to be signed, the signature is invalid. Also all commits must be signed not just the last one. So you either squash everything or change the commit history and sign all of them.

**Comment by justkawal** [comment]
Signed all.

**Review by leonardocustodio — APPROVED** [review]

**Comment by leonardocustodio** [comment]
@justkawal can you try to rebase? Not sure why actions are not running

**Comment by justkawal** [comment]
Did rebase again.

**Review by leonardocustodio — APPROVED** [review]

**Pull request merged**
